// -------------------------------------------------------------
// 
// File Name: adpcm\adpcm_precision_study\ADPCM_Decoder.v
// Created: 2022-04-30 23:31:54
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: ADPCM_Decoder
// Source Path: adpcm_precision_study/adpcm/adpcm encoder2/ADPCM Decoder
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module ADPCM_Decoder
          (clk,
           reset,
           enb,
           In1,
           LoopGain,
           Out1);


  input   clk;
  input   reset;
  input   enb;
  input   signed [15:0] In1;  // sfix16_En12
  input   signed [19:0] LoopGain;  // sfix20_En16
  output  signed [15:0] Out1;  // sfix16_En12


  wire signed [15:0] Step_Size;  // sfix16_En12
  wire signed [15:0] Integrator_gain_0_99_out1;  // sfix16_En12


  Step_Size_Adaptor1_block u_Step_Size_Adaptor1 (.clk(clk),
                                                 .reset(reset),
                                                 .enb(enb),
                                                 .in(In1),  // sfix16_En12
                                                 .out(Step_Size)  // sfix16_En12
                                                 );

  Integrator_gain_0_99_block u_Integrator_gain_0_99 (.clk(clk),
                                                     .reset(reset),
                                                     .enb(enb),
                                                     .StepSize(Step_Size),  // sfix16_En12
                                                     .LoopGain(LoopGain),  // sfix20_En16
                                                     .Out1(Integrator_gain_0_99_out1)  // sfix16_En12
                                                     );

  assign Out1 = Integrator_gain_0_99_out1;

endmodule  // ADPCM_Decoder

