open_system('adpcm_precision_study');
open_system('gm_adpcm_precision_study');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_adpcm_precision_study/adpcm/ADPCM Decoder1/Integrator -- gain = 0.99/Product', 'user1');
hilite_system('adpcm_precision_study/adpcm/ADPCM Decoder1/Integrator -- gain = 0.99/Product', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_adpcm_precision_study/adpcm/ADPCM Decoder1/Integrator -- gain = 0.99/Sum2', 'user1');
hilite_system('adpcm_precision_study/adpcm/ADPCM Decoder1/Integrator -- gain = 0.99/Sum2', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_adpcm_precision_study/adpcm/ADPCM Decoder1/Integrator -- gain = 0.99/Delay', 'user1');
hilite_system('adpcm_precision_study/adpcm/ADPCM Decoder1/Integrator -- gain = 0.99/Delay', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_adpcm_precision_study/adpcm/adpcm encoder2/ADPCM Decoder/Integrator -- gain = 0.99/Delay', 'user1');
hilite_system('adpcm_precision_study/adpcm/adpcm encoder2/ADPCM Decoder/Integrator -- gain = 0.99/Delay', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_adpcm_precision_study/adpcm/adpcm encoder2/ADPCM Decoder/Integrator -- gain = 0.99/Delay', 'user1');
hilite_system('adpcm_precision_study/adpcm/adpcm encoder2/ADPCM Decoder/Integrator -- gain = 0.99/Delay', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_adpcm_precision_study/adpcm/adpcm encoder2/ADPCM Decoder/Integrator -- gain = 0.99/Product', 'user1');
hilite_system('adpcm_precision_study/adpcm/adpcm encoder2/ADPCM Decoder/Integrator -- gain = 0.99/Product', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_adpcm_precision_study/adpcm/adpcm encoder2/ADPCM Decoder/Integrator -- gain = 0.99/Product', 'user1');
hilite_system('adpcm_precision_study/adpcm/adpcm encoder2/ADPCM Decoder/Integrator -- gain = 0.99/Product', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_adpcm_precision_study/adpcm/adpcm encoder2/ADPCM Decoder/Integrator -- gain = 0.99/Sum2', 'user1');
hilite_system('adpcm_precision_study/adpcm/adpcm encoder2/ADPCM Decoder/Integrator -- gain = 0.99/Sum2', 'user1');
cs.HiliteType = 'user1';
cs.ForegroundColor = 'black';
cs.BackgroundColor = 'cyan';
set_param(0, 'HiliteAncestorsData', cs);
hilite_system('gm_adpcm_precision_study/adpcm/adpcm encoder2/ADPCM Decoder/Integrator -- gain = 0.99/Sum2', 'user1');
hilite_system('adpcm_precision_study/adpcm/adpcm encoder2/ADPCM Decoder/Integrator -- gain = 0.99/Sum2', 'user1');
