// -------------------------------------------------------------
// 
// File Name: adpcm\adpcm_precision_study\Subsystem.v
// Created: 2022-04-30 23:31:54
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem
// Source Path: adpcm_precision_study/adpcm/ADPCM Decoder1/Step Size Adaptor1/Subsystem
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem
          (In1,
           In2,
           Out1);


  input   In1;
  input   signed [15:0] In2;  // sfix16_En12
  output  signed [15:0] Out1;  // sfix16_En12


  wire switch_compare_1;
  wire signed [15:0] Constant3_out1;  // sfix16_En12
  wire signed [15:0] Constant1_out1;  // sfix16_En12
  wire signed [15:0] Switch_out1;  // sfix16_En12
  wire signed [31:0] Product1_mul_temp;  // sfix32_En24
  wire signed [15:0] Product1_out1;  // sfix16_En12


  assign switch_compare_1 = In1 == 1'b1;



  assign Constant3_out1 = 16'sb0000100000000000;



  assign Constant1_out1 = 16'sb0010000000000000;



  assign Switch_out1 = (switch_compare_1 == 1'b0 ? Constant3_out1 :
              Constant1_out1);



  assign Product1_mul_temp = Switch_out1 * In2;
  assign Product1_out1 = ((Product1_mul_temp[31] == 1'b0) && (Product1_mul_temp[30:27] != 4'b0000) ? 16'sb0111111111111111 :
              ((Product1_mul_temp[31] == 1'b1) && (Product1_mul_temp[30:27] != 4'b1111) ? 16'sb1000000000000000 :
              Product1_mul_temp[27:12] + $signed({1'b0, Product1_mul_temp[31] & (|Product1_mul_temp[11:0])})));



  assign Out1 = Product1_out1;

endmodule  // Subsystem

