// -------------------------------------------------------------
// 
// File Name: adpcm\adpcm_precision_study\Subsystem_block1.v
// Created: 2022-04-30 23:31:54
// 
// Generated by MATLAB 9.10 and HDL Coder 3.18
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_block1
// Source Path: adpcm_precision_study/adpcm/adpcm encoder2/Subsystem
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_block1
          (In1,
           Out1,
           Out2);


  input   signed [15:0] In1;  // sfix16_En12
  output  signed [1:0] Out1;  // sfix2
  output  signed [15:0] Out2;  // sfix16_En12


  wire signed [15:0] Sign_out1;  // int16
  wire signed [1:0] Data_Type_Conversion1_out1;  // sfix2
  wire signed [15:0] Data_Type_Conversion_out1;  // sfix16_En12

  // sign extraction


  assign Sign_out1 = (In1 > 16'sb0000000000000000 ? 16'sb0000000000000001 :
              (In1 < 16'sb0000000000000000 ? 16'sb1111111111111111 :
              16'sb0000000000000000));



  assign Data_Type_Conversion1_out1 = ((Sign_out1[15] == 1'b0) && (Sign_out1[14:1] != 14'b00000000000000) ? 2'sb01 :
              ((Sign_out1[15] == 1'b1) && (Sign_out1[14:1] != 14'b11111111111111) ? 2'sb10 :
              $signed(Sign_out1[1:0])));



  assign Out1 = Data_Type_Conversion1_out1;

  assign Data_Type_Conversion_out1 = ((Sign_out1[15] == 1'b0) && (Sign_out1[14:3] != 12'b000000000000) ? 16'sb0111111111111111 :
              ((Sign_out1[15] == 1'b1) && (Sign_out1[14:3] != 12'b111111111111) ? 16'sb1000000000000000 :
              {Sign_out1[3:0], 12'b000000000000}));



  assign Out2 = Data_Type_Conversion_out1;

endmodule  // Subsystem_block1

