// -------------------------------------------------------------
// 
// File Name: Piplined_encoder\adpcm_precision_study\ADPCM_Decoder.v
// Created: 2022-04-30 14:10:34
// 
// Generated by MATLAB 9.11 and HDL Coder 3.19
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: ADPCM_Decoder
// Source Path: adpcm_precision_study/ADPCM_ECD/adpcm encoder2/ADPCM Decoder
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module ADPCM_Decoder
          (clk,
           reset,
           enb,
           In1,
           LoopGain,
           Out1);


  input   clk;
  input   reset;
  input   enb;
  input   signed [19:0] In1;  // sfix20_En16
  input   signed [27:0] LoopGain;  // sfix28_En24
  output  signed [19:0] Out1;  // sfix20_En16


  wire signed [19:0] Step_Size;  // sfix20_En16
  wire signed [19:0] Integrator_gain_0_99_out1;  // sfix20_En16


  Step_Size_Adaptor1_block u_Step_Size_Adaptor1 (.clk(clk),
                                                 .reset(reset),
                                                 .enb(enb),
                                                 .in(In1),  // sfix20_En16
                                                 .out(Step_Size)  // sfix20_En16
                                                 );

  Integrator_gain_0_99_block u_Integrator_gain_0_99 (.clk(clk),
                                                     .reset(reset),
                                                     .enb(enb),
                                                     .StepSize(Step_Size),  // sfix20_En16
                                                     .LoopGain(LoopGain),  // sfix28_En24
                                                     .Out1(Integrator_gain_0_99_out1)  // sfix20_En16
                                                     );

  assign Out1 = Integrator_gain_0_99_out1;

endmodule  // ADPCM_Decoder

