// -------------------------------------------------------------
// 
// File Name: Piplined_encoder\adpcm_precision_study\current_previous.v
// Created: 2022-04-30 14:10:34
// 
// Generated by MATLAB 9.11 and HDL Coder 3.19
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: current_previous
// Source Path: adpcm_precision_study/ADPCM_ECD/ADPCM Decoder1/Step Size Adaptor1/current - previous
// Hierarchy Level: 3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module current_previous
          (clk,
           reset,
           enb,
           In1,
           Out1);


  input   clk;
  input   reset;
  input   enb;
  input   signed [19:0] In1;  // sfix20_En16
  output  Out1;


  reg signed [19:0] Delay_out1;  // sfix20_En16
  wire signed [20:0] Sum1_sub_cast;  // sfix21_En16
  wire signed [20:0] Sum1_sub_cast_1;  // sfix21_En16
  wire signed [20:0] Sum1_sub_temp;  // sfix21_En16
  wire signed [19:0] Sum1_out1;  // sfix20_En16
  wire signed [19:0] Constant5_out1;  // sfix20_En16
  wire Relational_Operator5_relop1;


  always @(posedge clk or posedge reset)
    begin : Delay_process
      if (reset == 1'b1) begin
        Delay_out1 <= 20'sb00000000000000000000;
      end
      else begin
        if (enb) begin
          Delay_out1 <= In1;
        end
      end
    end



  assign Sum1_sub_cast = {In1[19], In1};
  assign Sum1_sub_cast_1 = {Delay_out1[19], Delay_out1};
  assign Sum1_sub_temp = Sum1_sub_cast - Sum1_sub_cast_1;
  assign Sum1_out1 = ((Sum1_sub_temp[20] == 1'b0) && (Sum1_sub_temp[19] != 1'b0) ? 20'sb01111111111111111111 :
              ((Sum1_sub_temp[20] == 1'b1) && (Sum1_sub_temp[19] != 1'b1) ? 20'sb10000000000000000000 :
              $signed(Sum1_sub_temp[19:0])));



  assign Constant5_out1 = 20'sb00000000000000000000;



  assign Relational_Operator5_relop1 = Sum1_out1 == Constant5_out1;



  assign Out1 = Relational_Operator5_relop1;

endmodule  // current_previous

