// -------------------------------------------------------------
// 
// File Name: Piplined_encoder\adpcm_precision_study\Subsystem_block.v
// Created: 2022-04-30 14:10:34
// 
// Generated by MATLAB 9.11 and HDL Coder 3.19
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_block
// Source Path: adpcm_precision_study/ADPCM_ECD/adpcm encoder2/ADPCM Decoder/Step Size Adaptor1/Subsystem
// Hierarchy Level: 4
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_block
          (In1,
           In2,
           Out1);


  input   In1;
  input   signed [19:0] In2;  // sfix20_En16
  output  signed [19:0] Out1;  // sfix20_En16


  wire switch_compare_1;
  wire signed [19:0] Constant3_out1;  // sfix20_En16
  wire signed [19:0] Constant1_out1;  // sfix20_En16
  wire signed [19:0] Switch_out1;  // sfix20_En16
  wire signed [39:0] Product1_mul_temp;  // sfix40_En32
  wire signed [19:0] Product1_out1;  // sfix20_En16


  assign switch_compare_1 = In1 == 1'b1;



  assign Constant3_out1 = 20'sb00001000000000000000;



  assign Constant1_out1 = 20'sb00100000000000000000;



  assign Switch_out1 = (switch_compare_1 == 1'b0 ? Constant3_out1 :
              Constant1_out1);



  assign Product1_mul_temp = Switch_out1 * In2;
  assign Product1_out1 = ((Product1_mul_temp[39] == 1'b0) && (Product1_mul_temp[38:35] != 4'b0000) ? 20'sb01111111111111111111 :
              ((Product1_mul_temp[39] == 1'b1) && (Product1_mul_temp[38:35] != 4'b1111) ? 20'sb10000000000000000000 :
              Product1_mul_temp[35:16] + $signed({1'b0, Product1_mul_temp[39] & (|Product1_mul_temp[15:0])})));



  assign Out1 = Product1_out1;

endmodule  // Subsystem_block

