// -------------------------------------------------------------
// 
// File Name: Piplined_encoder\adpcm_precision_study\Subsystem_block1.v
// Created: 2022-04-30 14:10:34
// 
// Generated by MATLAB 9.11 and HDL Coder 3.19
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Subsystem_block1
// Source Path: adpcm_precision_study/ADPCM_ECD/adpcm encoder2/Subsystem
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Subsystem_block1
          (In1,
           Out1,
           Out2);


  input   signed [19:0] In1;  // sfix20_En16
  output  signed [1:0] Out1;  // sfix2
  output  signed [19:0] Out2;  // sfix20_En16


  wire signed [19:0] Sign_out1;  // sfix20
  wire signed [1:0] Data_Type_Conversion1_out1;  // sfix2
  wire signed [19:0] Data_Type_Conversion_out1;  // sfix20_En16

  // sign extraction


  assign Sign_out1 = (In1 > 20'sb00000000000000000000 ? 20'sb00000000000000000001 :
              (In1 < 20'sb00000000000000000000 ? 20'sb11111111111111111111 :
              20'sb00000000000000000000));



  assign Data_Type_Conversion1_out1 = ((Sign_out1[19] == 1'b0) && (Sign_out1[18:1] != 18'b000000000000000000) ? 2'sb01 :
              ((Sign_out1[19] == 1'b1) && (Sign_out1[18:1] != 18'b111111111111111111) ? 2'sb10 :
              $signed(Sign_out1[1:0])));



  assign Out1 = Data_Type_Conversion1_out1;

  assign Data_Type_Conversion_out1 = ((Sign_out1[19] == 1'b0) && (Sign_out1[18:3] != 16'b0000000000000000) ? 20'sb01111111111111111111 :
              ((Sign_out1[19] == 1'b1) && (Sign_out1[18:3] != 16'b1111111111111111) ? 20'sb10000000000000000000 :
              {Sign_out1[3:0], 16'b0000000000000000}));



  assign Out2 = Data_Type_Conversion_out1;

endmodule  // Subsystem_block1

